
<script src="http://code.jquery.com/jquery-1.10.2.min.js"
	type="text/javascript"></script>
<script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.js"
	type="text/javascript"></script>
<script>


$(document).ready(function() {
    $('#example').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "/owner/json/browse/location_id/<?php echo $this->locationId?>"
    } );
    
} );
<?php if($this->locationId):?>

function f1(id)
{
  var ownerType = $("#ownerType_" + id + " option:selected").text();	 
  var url = "owner_id/" + id + "/owner_type/" + ownerType + "/location_id/" + <?php echo $this->locationId?>;
  window.location.href = "/owner/add/location/" + url;
   //form validation that recalls the page showing with supplied inputs.    
}
<?php endif;?>
</script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	
    <div class="box round first fullpage">
		<h2>Browse For Contacts</h2>
		<div class="block">
		 
			<table id="example" class="display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>Name</th>
						<th>Phone</th>
						<th>Street</th>
						<th>city</th>
						<th>state</th>
						<th>zip</th>
						<?php if($this->locationId):?>
						<th></th>
						<th></th>
						<?php endif;?>
					</tr>
				</thead>
				
			</table>
			<div class="clear"></div>
			
		</div>
		<div class="clear"></div>
	</div>
    	
</div>
<div class="grid_3">

<?php echo $this->recent(0);?>
</div>
<div class="clear"></div>