<script src="/js/ajax/owner.js" type="text/javascript"></script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Owners</h2>
		<div class="block">
		
			<div class="SearchPanel">
				<div class="grid_8 pad_4">Enter a name to search. Results will be displayed in the Selection box</div>
				<div class="clear"></div>
				
				<form action="/owner/index" class="searchForm" accept-charset="utf-8" method="post">
					<div class="grid_6 pad_4">
						<b>Name:</b> <input type="text" name="owner" id="owner" value="" class="medium" maxlength="300" tabindex="1" autocomplete="off" />
						<input type="submit" name="search" value="Search" class=""/>
						<div class="ownerAutoComplete auto"><ul></ul></div>
					</div>
					<div class="clear"></div>
					<div class="buttons">
						
					</div>
					
				</form>
			</div>
			<div class="clear"></div>
			
		</div>
	</div>
</div>
<div class="grid_3">

<?php echo $this->recent(0);?>
</div>
<div class="clear"></div>