<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Edit Service Date for Location <?php echo $this->location->street;?></h2>
		<div class="block">
			<?php if($this->form->getMessages()) {?>
				<div class="message error">
                	<h5>Error!</h5>
                    <p>
                    	The following errors where found:<br /><br />
                    	<?php foreach($this->form->getMessages() as $message) {?>
                    		<?php foreach($message as $error) {?>
                    			<?php echo$error ?> <br />
                    		<?php }?>
                    	<?php }?>
                    	<br />
                    	Please correct the above errors and save your information.
                    </p>
                </div>
                <br />
			<?php } else {?>
				<div class="message info">
            	<h5>Information</h5>
            	<?php if(!empty($this->schedule)) {?>
                <p>Your about to change the next Service Due date from <?php echo date("M d, Y", $this->schedule->service_due)?>.</p>
                <?php } else {?>
                <p>Create a New Service Date.</p>
                <?php }?>
            </div>
			<?php }?>
				<form method="post" action="">
					<div class="grid_6 pad_4"><?php echo $this->form->getElement('date');?></div>
					<div class="clear"></div>
		
					
					<div class="grid_4 pad_4">
						<?php echo $this->form->getElement('no_csrf');?>
						<?php echo $this->form->getElement('submit');?>
					</div>
					<div class="clear"></div>
				</form>
			
			<br />
			<div class="buttons">
				<a href="/location/view/index/id/<?php echo $this->location->id;?>" class="button left" title="Back to Location"><span class="icon icon108"></span></a>
			</div>
		</div>
	</div>
</div>

<div class="grid_3">
	<?php echo $this->recent($this->location->id);?>
</div>
<div class="clear"></div>