<?php echo $this->MainNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>Controller <?php echo $this->module->name;?>::<?php echo $this->controller->name;?></h2>
		<div class="block">
			<p>
				<b>Module Name:</b> <a href="/admin/module/view/id/<?php echo $this->module->module_id;?>"><?php echo $this->module->name;?></a><br />
				<b>Controller Name: </b> <?php echo $this->controller->name?>
			</p>
		</div>
		
		<table class="data display">
			<thead>
					<tr>
						<th>Id</th>
						<th>Action Name</th>
						<th>Auth</th>
						<th>Acl</th>
						<th>Title</th>
						<th></th>
					</tr>
			</thead>
			<tbody>
				<?php $i = 0;?>
				<?php foreach($this->actions as $action) {?>
				<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
					<td><?php echo $action->action_id;?></td>
					<td><?php echo $action->name;?></td>
					<td><?php echo $action->auth;?></td>
					<td><?php echo $action->acl;?></td>
					<td><?php echo $action->meta_title;?></td>
					<td>
						<a style="float:right" href="/admin/module/edit-action/id/<?php echo $action->action_id?>" class="button left" title="Edit Action"><span class="icon icon145"></span></a><br />
						
					</td>
				</tr>
				<?php $i++; ?>
				<?php }?>	
			</tbody>
		</table>
		<div class="clear"></div>
		<div class="buttons">
			<a href="/admin/module" class="button left" title="Module Home"><span class="icon icon53"></span></a>
			<a href="/admin/module/add-action/id/<?php echo $this->controller->controller_id?>" class="button left" title="Add Action"><span class="icon icon3"></span></a><br />
						
		</div>
	</div>
</div>