<?php echo $this->AdminNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>Edit Module <?php echo $this->module->name; ?></h2>
		<div class="block">
			<div class="buttons">
				<a href="/admin/index/" class="button left" title="Admin Home"><span class="icon icon108"></span></a>
				<a href="/admin/module" class="button left" title="Module Home"><span class="icon icon53"></span></a>
					
			</div>
		</div>
	</div>
</div>