<?php echo $this->MainNav();?>
<div class="clear"></div>
<div class="grid_16">
	<div class="box round first fullpage">
 		<h2>Quinn's Well and Pump Service</h2>
        <div class="block">
        	<h3>Welcome to Well Log Pro</h3>
        
           	<p>
           		Change Log:
           		<ul>
           			<li>1/14/14 - Removed Service Due Warning from Location Page.</li>
           			<li>1/14/14 - Added Service Status to the location page.</li>
           			<li>1/14/14 - Added Technician to service on location page.</li>
           			<li>1/14/14 - If Service status is open then Service Complaint is shown. If Closed then Service Prefromed is shown.</li>
           			<li>1/14/14 - Removed Auto Complete for fields State and city on Location Add and Location update.</li>
           			<li>1/14/14 - It was requested to put a link back to the location on the View Owner page. There is already a link back to the Location under the locations section below the Owner details</li>
           			<li>1/14/14 - Removed Notes page from the Service PDF</li>
           			<li>1/14/14 - Changed Token Timout value to 1 hour, set session timeout value to 1 day.</li>
           		</ul>
           	</p>
           	<br />	<br />	<br />
			
		</div>
	</div>
</div>
<div class="clear"></div>








