<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>
			Delete Location
			<?php echo $this->location->street?>
			<?php echo $this->location->city?>
		</h2>
		<div class="block">

			<?php if ($this->hideForm): ?>
			<p>The location was successfully deleted.</p>
			<?php else: ?>
			
			<p>
				Are you sure you want to delete the location <strong><?php echo $this->location->street?>
					<?php echo $this->location->city?> </strong>? <br /> This will
				completly remove all information associated with this location
				including location details, pump information, pump tests and service
				records. <br /> <strong>This action cannot be un-done and is
					permanent</strong>
			</p>
			<?php echo $this->form;?>
			<?php endif;?>
		</div>
	</div>
</div>
<div class="clear"></div>
