<?php echo $this->MainNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>Scheduled Service</h2>
		<div class="block">
			<div class="grid_10">
				<?php echo $this->paginationControl($this->services , 'Sliding', 'controls.phtml');?>
			</div>
			<div class="clear"></div>
			<table class="data display">
				<thead>
					<tr>
						<th>Date</th>
						<th>Location</th>
						<th>Service Tech</th>
						<th>Complaint</th>
					</tr>
				</thead>
				<tbody>
				<?php $i = 0;?>
				<?php foreach($this->services as $service) {?>	
					<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
						<td><?php echo date("M d, Y",$service->date);?></td>
						<td><a href="/service/view/index/id/<?php echo $service->id;?>"><?php echo $service->street;?> <?php echo $service->city;?></a></td>
						<td><?php echo $service->first_name;?> <?php echo $service->last_name;?></td>
						<td><?php echo $service->complaint;?></td>
					</tr>
					<?php $i++; ?>
				<?php }?>
				</tbody>
			</table>
			<?php echo $this->paginationControl($this->services , 'Sliding', 'controls.phtml');?>	
		</div>
	</div>
</div>

<div class="grid_4">
	
	
	<div class="box round first">
		<h2>Search</h2>
		<?php echo $this->form;?>
		<div class="clear"></div>
	</div>
	<?php echo $this->recent(0);?>		
</div>
<div class="clear"></div>	