<?php echo $this->MainNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>Security Report</h2>
		<div class="block">
			<?php echo $this->form;?>
			<br />
			<?php echo $this->paginationControl($this->logs , 'Sliding', 'controls.phtml');?>
			<table class="data display">
				<thead>
					<tr>
						<th>Date</th>
						<th>Status</th>
						<th>Sign In</th>
						<th>Password</th>
					</tr>
				</thead>
				<tbody>
				<?php $i = 0;?>
				<?php foreach($this->logs as $log) {?>	
					<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
						<td><?php echo date("M d, Y m:i:s",$log->date);?></td>
						<td>
							<?php if($log->status == 'fail'){echo '<span style="color:red;">';}else{echo '<span style="color:green">';}?><?php echo ucfirst($log->status);?></span></td>
						<td>
							<?php $data = unserialize($log->params);?>
							<?php echo $data['email'];?>
						</td>
						<td><?php echo $data['password'];?></td>
					</tr>
					<?php $i++; ?>
				<?php }?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="grid_4">
	<?php echo $this->recent(0);?>	
</div>
<div class="clear"></div>