<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Error</h2>
		<div class="block">
		<div class="message error">
                	<h5>Error!</h5>
                    <p>The following error was thrown: <br />
                    	<b><?php echo $this->msg;?></b><br /></p>
        </div>
                    
		
		<div class="buttons">
				<a href="/admin/list/index" class="button left" title="Back to Admin Lists"><span class="icon icon120"></span></a>
				<a href="/city/admin/add" class="button middle" title="Add New City"><span class="icon icon3"></span></a>
				<a href="/city/admin/list" class="button right" title="Back to City Lists"><span class="icon icon8"></span></a>
			
			</div>
		</div>
	</div>
</div>