<script src="/js/fields/owner.js" type="text/javascript"></script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Delete Pump Test at Location <?php echo $this->location->street;?></h2>
		<div class="block">
			<?php if($this->form->getMessages()) {?>
				<div class="message error">
                	<h5>Error!</h5>
                    <p>
                    	The following errors where found:<br /><br />
                    	<?php foreach($this->form->getMessages() as $message) {?>
                    		<?php foreach($message as $error) {?>
                    			<?php echo$error ?> <br />
                    		<?php }?>
                    	<?php }?>
                    	<br />
                    	Please correct the above errors and save your information.
                    </p>
                </div>
			<?php } ?>
			<div class="message warning">
			
			<p>Are you sure you want to delete the pump test entered on <?php echo date("m-d-y", $this->pumpTest->date)?> 
			</div>
			
			<?php echo $this->form;?>
			<div class="buttons">
			 <a href="/location/view/index/id/<?php echo $this->location->id;?>" class="button left" title="Back to Location"><span class="icon icon108"></span></a>
				
			</div>
		</div>
	</div>
</div>
<div class="grid_3">
<?php echo $this->ServiceDue($this->location->id);?>
<?php echo $this->recent($this->location->id);?>
</div>
<div class="clear"></div>