<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headMeta();?>
		<!-- @todo Create plug in to load theme files from a config param -->
		<link rel="stylesheet" type="text/css" href="/css/reset.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/text.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/960.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/layout.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/nav.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/css3-buttons.css" media="screen" />
	    <link rel="stylesheet" type="text/css" href="/css/tiptip.css"   media="screen" />
	    <!--  <link rel="stylesheet" type="text/css" href="/css/table/demo_page.css"   />-->
	    
	   
	    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
	    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
		
		
	    <script src="/js/jquery-1.6.4.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.ui.core.min.js" type="text/javascript" ></script>
		<script src="/js/table/jquery.dataTables.min.js" type="text/javascript"></script>		
		<script src="/js/jquery-ui/jquery.ui.widget.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.ui.accordion.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.effects.core.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.effects.slide.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.ui.mouse.min.js" type="text/javascript"></script>
		<script src="/js/jquery-ui/jquery.ui.sortable.min.js" type="text/javascript"></script>
		
		<?php /**
		<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
		<script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.js" type="text/javascript"></script>
		
		*/?>
		
		<script src="/js/common.js" type="text/javascript"></script>
		
		<!-- Load TinyMCE -->
    <script src="/js/tiny-mce/jquery.tinymce.js" type="text/javascript"></script>
    <script type="text/javascript">
        
    </script>
    <!-- /TinyMCE -->
 
		<?php echo $this->jQuery(); ?>
		
  	    <script>
			$(document).ready(function() {
			
				// Toggle the dropdown menu's
				$(".dropdown .button, .dropdown button").click(function () {
					if (!$(this).find('span.toggle').hasClass('active')) {
						$('.dropdown-slider').slideUp();
						$('span.toggle').removeClass('active');
					}
	       
	        // open selected dropown
					$(this).parent().find('.dropdown-slider').slideToggle('fast');
					$(this).find('span.toggle').toggleClass('active');
					
					return false;
				});
				
			
			
			});
			
			// Close open dropdown slider by clicking elsewhwere on page
			$(document).bind('click', function (e) {
				if (e.target.id != $('.dropdown').attr('class')) {
					$('.dropdown-slider').slideUp();
					$('span.toggle').removeClass('active');
				}
			});
  		</script>
 		
	</head>
<body>
	<div id="dhtmltooltip"></div>
	<div class="container_16" >
	
		<div class="grid_16 header-repeat">
            <div id="branding">
                <div class="floatleft"><img src="/images/QuinnsLogo.png" /></div>
                <div class="floatright">
 					<div class="floatleft"><img src="/img/img-profile.jpg" alt="Profile Pic" /></div>
                    <div class="floatleft marginleft10">
                    	<?php if($this->auth()->hasIdentity()) {?>
                    	<?php $param = $this->auth()->getIdentity();?>	
	                        <ul class="inline-ul floatleft"> 
	                        <?php if($param['type'] == 'employee') {?>
	                        	<li><?php echo $param['firstName'] ?> <?php echo $param['lastName'] ?></li>
	                            <li><a href="/employee/index">Home</a></li>
	                            <li><a href="/auth/signout">Logout</a></li>
	                        <?php } else {?>
	                        	<li><?php echo $param['firstName'] ?> <?php echo $param['lastName'] ?></li>
	                        	<li><a href="/client/portal/index">Home</a></li>
	                            <li><a href="/auth/signout">Logout</a></li>
	                        <?php }?>
	                        </ul>
	                        <br />
	                        <span class="small grey"></span>
                        <?php } else {?>
                        <ul class="inline-ul floatleft">
                        	<li>Guest</li>
                        	<li><a href="/auth/signin">Sign In</a></li>
                        </ul>
                        <?php }?>
                    </div>
				</div>
                <div class="clear"></div>
            </div>
		</div>
		<div class="clear"></div>	
		
		<?php echo $this->layout()->content; ?>
	
		
		<div class="clear"></div>
		
		<div id="site_info">
	       <div class="grid_4">
	       	<div class="block">
	       		<h5>Company Pages</h5>
	       		<ul>
	       			<li><a href="/">Home</a></li>
	       			<li><a href="/page/about">About Well Log Pro</a></li>
	       			<?php $uri = str_replace("/", ":", Zend_Controller_Front::getInstance()->getRequest()->getRequestUri())?>
	       			<li><a href="/report/audit/page/uri/<?php echo urlencode( $uri );?>">Page History</a></li>
	       		</ul>
	       	</div>
			</div>
		</div>
	</div>

	
</body>
			
		
		
		
			
</html>