<?php echo $this->MainNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>Audit System</h2>
		<div class="block">
			<?php echo $this->form;?>
			<br />
			<?php echo $this->paginationControl($this->logs , 'Sliding', 'controls.phtml');?>
			<table class="data display">
				<thead>
					<tr>
						<th>Date</th>
						<th>Employee</th>
						<th>Request URI</th>
					</tr>
				</thead>
				<tbody>
				<?php $i = 0;?>
				<?php foreach($this->logs as $log) {?>	
					<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
							<td><a href="/report/audit/view/id/<?php echo $log->id;?>" title="View Details"><?php echo date("M d, Y h:i:s", $log->date);?></a></td>
							<td><?php echo $log->first_name;?> <?php echo $log->last_name;?></td>
							<td>
								<a href="<?php echo $log->uri;?>"><?php echo $log->uri;?></a>
							</td>
						</tr>
					<?php $i++; ?>
				<?php }?>
				</tbody>
			</table>
			<?php echo $this->paginationControl($this->logs , 'Sliding', 'controls.phtml');?>
		</div>
	</div>
</div>
<div class="grid_4">
	<?php echo $this->recent(0);?>	
</div>
<div class="clear"></div>