<?php echo $this->MainNav();?>
<div class="grid_12">
	<div class="box round first fullpage">
		<h2>View Audit Report</h2>
		<div class="block">
			<div class="grid_4 pad_4"><b>Date Request:</b> <?php echo date("M d, Y h:i:s", $this->changeLog->date);?></div>
			<div class="grid_4 pad_4"><b>Requested By:</b> <?php echo $this->changeLog->first_name;?> <?php echo $this->changeLog->last_name;?></div>
			<div class="clear"></div>
			<div class="grid_2 pad_4"><b>Module:</b> <?php echo $this->changeLog->module;?></div>
			<div class="grid_2 pad_4"><b>Controller:</b> <?php echo $this->changeLog->controller;?></div>
			<div class="grid_2 pad_4"><b>Controller:</b> <?php echo $this->changeLog->action;?></div>
			<div class="grid_2 pad_4"><b>ID:</b> <?php echo $this->changeLog->request_id;?></div>
			<div class="clear"></div>
			<div class="grid_10 pad_4"><b>Request URI:</b> <a href="<?php echo $this->changeLog->uri;?>"><?php echo $this->changeLog->uri;?></a></div>
			<div class="clear"></div>
			<div class="grid_2 pad_4"><b>Params:</b></div>
			<div class="clear"></div>
			<div class="grid_8 pad_4">
				<?php $params = unserialize($this->changeLog->params);?>
				<pre><?php print_r($params)?></pre>	
			</div>
			<div class="clear"></div>
			<div class="grid_2 pad_4"><b>Request:</b></div>
			<div class="clear"></div>
			<?php $requestData = unserialize($this->changeLog->request);?>
			<div class="grid_8 pad_4">
				<pre><?php print_r($requestData)?></pre>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="grid_4">
	<?php echo $this->recent(0);?>	
</div>
<div class="clear"></div>