<?php if($this->auth()->hasIdentity()) {?>
	<?php $param = $this->auth()->getIdentity();?>
		<?php echo $this->MainNav();?>
<?php } ?>
<?php echo $this->breadcrumb($this->breadcrumb);?>
<div class="clear"></div>
<div class="grid_16">
	<div class="box round first fullpage">
 		<h2>About Innovative Support Solutions</h2>
 		 <div class="block">
 		 	<h4>About Us</h4>
 		 	<p class="start">
 		 		Innovative Support Services was founded in 2012 by Jaimie &amp; Christy Garner, Andrew Garner and Rob Johnson. 
 		 		Jaimie Garner has an extensive background in the Technical Support industry as well as a 
 		 		very extensive career in customer service and interfacing with customers on a daily basis. 
 		 		Innovative strives to stay up on all our technical skills but also pay close attention to 
 		 		the level of customer service we provide.</p>
 		 	<h4>Certifications</h4>
			<p>Our consultants are required to train and acquire an HDI Certification. This is one of the 
			industries most recognized customer service certifications. The training is extensive and the 
			certification requires a passing score of 90%. We are committed to bringing our customers a 
			pleasant and enjoyable experience. Taking the frustration from calling your IT provider for 
			help is our ultimate goal.</p>
			
			
			
 		 </div>
 	</div>
 </div>
 <div class="clear"></div>
 
 <div class="grid_16">
 	<div class="box round first fullpage">
 		<div class="block" style="height:125px;">
 			<img src="/images/We-are-Comptia-Certified.jpg" alt="No Contracts" class="left" height="58px"/>
 			<img src="/images/We-are-HDI-Certified.jpg" alt="No Contracts" class="left" height="73px"/>
 			<img src="/images/Microsoft-Certified-Professionals.gif" alt="No Contracts" class="left" height="78px"/>
 		</div>
 	</div>
 </div>