<?php if($this->auth()->hasIdentity()) {?>
	<?php $param = $this->auth()->getIdentity();?>
		<?php echo $this->MainNav();?>
<?php } ?>
<?php echo $this->breadcrumb($this->breadcrumb);?>
<div class="clear"></div>
<div class="grid_16">
	<div class="box round first fullpage">
		<h2>Hosted Exchange</h2>
		<img src="/images/Hosted-Exchange.png" alt="Hosted Exchange" class="left" border="0"/>
		 <div class="block">
		 	<p class="start">
		 		Innovative Support Services offers support for the latest version of Exchange – Exchange 2010! 
		 		Forget about maintaining your own Exchange Server or maintaining hardware. 
		 		We utilise Microsoft Office 365 solutions that are perfect for any business. Hosted Exchange solution 
		 		comes with unlimited support and is maintained by seasoned Exchange Administrators. 
		 		Our job is to keep email running and provide a reliable email solution for your business. 
		 	</p>
		 	
		 	<h4>Exchange Online: business-class email that's easy to manage</h4>
		 	<p>Built to deliver industry-leading security, Exchange Online provides hosted business-class 
		 		email, calendar, and contacts on your choice of devices and browsers for as little as $4 per 
		 		user per month, without the need to maintain a server. Exchange Online is available as a standalone 
		 		plan or as part of Office 365.</p>
		 	<h4>Top benefits</h4>
		 		<ul>
		 	    	<li>Stay connected no matter where you’re working. Access your email, calendars, and 
		 	    	contacts from your PC, tablet, phone, and web browser. View screenshot</li>

			    	<li>Focus on communicating. Get more done with 25 GB of storage per user mailbox and 
			    	the ability to send attachments up to 25 MB. (1 GB mailboxes for kiosk workers)</li>
			
			    	<li>Manage your email system efficiently. Manage user permissions, service settings, 
			    		and more with a simplified web interface and powerful management tools. View 
			    		screenshot</li>
			
			    	<li>Migrate with ease. Transferring your existing email system is simple with free 
			    		migration tools.</li>
			
			    	<li>Enjoy a rich, familiar email experience. Complete integration with Outlook helps 
			    		keep your users productive. And with mobile sync you can access and update your 
			    		info while on the go. View screenshot</li>
			
			    	<li>Get a winning combination of reliability, security, and support. Rely on 99.9%
			    		uptime guaranteed with a financially backed SLA, plus enterprise-grade anti-malware
			    		 and anti-spam protection, and live 24/7 IT-level phone support. Stay compliant 
			    		 with email archiving, retention policies, and optional legal hold.</li>
		 
		 	</ul>
		 </div>
	</div>
</div>