<?php if($this->auth()->hasIdentity()) {?>
	<?php $param = $this->auth()->getIdentity();?>
		<?php echo $this->MainNav();?>
<?php } ?>
<?php echo $this->breadcrumb($this->breadcrumb);?>
<div class="clear"></div>
<div class="grid_16">
	<div class="box round first fullpage">
 		<h2>IT Support In Grants Pass</h2>
        <div class="block">
        	<p class="start">
        		Innovative Support Services provides a broad range of IT Support 
        		to businesses in and around Grants Pass Oregon. Our technicians have a broad skill 
        		set and we make it our business to know different technologies. Call us 
        		Today at
        	</p> 
        </div>
	</div>
</div>
<div class="clear"></div>

<div class="grid_5">
	<div class="box round fullpage">
			<h2>Online Backup Solution</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/secure-online-backup.png" alt="Hosted Exchange" class="left" />
					Access data from multiple computers utilizing your offsite storage also 
					as a shared network drive. Really! 
					
				</p>
			</div>
		</div>
		
		<div class="box round fullpage">
			<h2>IT Security</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/it-security-content-filtering.png" alt="Hosted Exchange" class="left" />
					Protect your network and information with security solutions such as Web Filters, 
					Hardware Firewalls and Hard Drive Encryption.  
					
				</p>
			</div>
		</div>
		
		<div class="box round fullpage">
			<h2>Wireless Networking</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/wireless-netowrking.png" alt="Hosted Exchange" class="left" />
					Setup a wireless environment or add security to your existing wireless connection. 
					is your network secured? 
					
				</p>
			</div>
		</div>
</div>

<div class="grid_5">
	<div class="box round fullpage">
			<h2>Virus & Spyware Removal</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/virus-spyware-removal.png" alt="Hosted Exchange" class="left" />
					Infected? We provide remote Virus, Spyware, Adware removal services.  
					
				</p>
			</div>
		</div>
		
		<div class="box round fullpage">
			<h2>Date Recovery</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/data-recovery.png" alt="Hosted Exchange" class="left" />
					Need your valuable data recovered from a failed hard drive? Data Corruption? Lost Email? 
					We offer a free diagnostics check.  
					
				</p>
			</div>
		</div>
		
		<div class="box round fullpage">
			<h2>Web Desgin, Hosting, SEO</h2>
			<div class="block" style="height:150px">
				<p class="start">
					<img src="/images/web-hosting-design.png" alt="Hosted Exchange" class="left" />
					We Design, Build, Host and Optimize your website all in one complete package.   
					
				</p>
			</div>
		</div>
</div>

<div class="grid_6">
	<div class="box round fullpage" style="height:673px">
			<h2>IT Support</h2>
			<div class="block" >
				<ul class="menu">
					<li><a href="/page/network-support">Network Support and Maintenance</a></li>
					<li><a href="/page/onsite-support">Onsite Support</a></li>
					<li><a href="/page/data-recovery">Data Recovery</a></li>
					<li><a href="/page/mobile-support">Mobile Device Support</a></li>
					<li><a href="/page/hosted-exchange">Microsoft Exchange</a></li>
					<li><a href="/page/network-security">Firewall Installation and IT Security</a></li>
					<li><a href="/page/hardware-support">Hardware Support</a></li>
					<li><a href="/page/virus-removal">Virus Removal</a></li>
					<li><a href="/page/remote-support">Remote IT Support</a></li>
					<li><a href="/page/wireless-networking">Wireless Networking</a></li>
					<li><a href="">Desktop Installations</a></li>
					<li><a href="">Email Hosting</a></li>
					<li><a href="">Vendor Management</a></li>
					<li><a href="">Content Filtering</a></li>
					<li><a href="">IT Consulting</a></li>
					<li><a href="">Backup Solutions / Disaster Recovery</a></li>
					<li><a href="">Software Installation and Support</a></li>
					<li><a href="">Remote Access</a></li>
					<li><a href="">Data &amp; Voice Cable Installation</a></li>
					<li><a href="">Internet Connection Troubleshooting</a></li>
					<li><a href="">Google Apps Implimentation</a></li>
					<li><a href="">Virtualization</a></li>
				</ul>
			</div>
		</div>
</div>
