<?php if($this->auth()->hasIdentity()) {?>
	<?php $param = $this->auth()->getIdentity();?>
		<?php echo $this->MainNav();?>
<?php } ?>
<?php echo $this->breadcrumb($this->breadcrumb);?>
<div class="clear"></div>
<div class="grid_16">
	<div class="box round first fullpage">
 		<h2>Managed Services in Grants Pass</h2>
        <div class="block">
        	<img src="/images/prineville-11.jpg" alt="No Contracts" class="right" height="300px"/>
        	<p class="start">Essentially Managed IT Services, is the continuous monitoring of network 
        	devices in your environment. These devices consist of anything from Computer Desktops to 
        	Servers and even Firewall Routers. We deploy the Managed IT Services agent into your 
        	environment and we are constantly updated when a problem arises.</p>

			<p>This way we can detect an issue as it happens in real time many times before the customer 
			even notices an issue. We will respond immediately to an issue and in most cases potential 
			problems are resolved before the customer is even aware. This gives our customer peace of mind 
			and they can get on with their daily duties without the hassle of worrying whether their 
			network is running at peak performance.</p>

			<p>Since our plans will be a fixed monthly fee, the advantage to the customer is not only a 
			significant reduction in their IT costs but lowering the need to augment their staff as well. 
			By offsetting many of the IT tasks to us and our Monitoring services, the need for an IT 
			administrator is greatly reduced thus saving the customer money and driving IT costs down.</p>

			<p>We have several options for this type of Managed IT Services solution or can customize one 
			specific to your needs. We would be glad to give you more information and go over all of the 
			benefits of a Monitoring plans.</p>

			<p>At Innovation, we value our customer's. We will go above and beyond to resolve your IT 
			issues and always share our knowledge with you. We pride ourselves in bringing an Excellent 
			Customer Experience to our clients and encourage you to settle for nothing less. We are so 
			confident in the level of services and the experience we bring to IT Outsourcing, we offer 
			Managed IT Service plans with NO LONG TERM CONTRACTS. Locking customers down for a year 
			is not the way we do business. We want our customers to call upon us not because of 
			contractual obligation, but because we offer the best support possible. Get started on a
			 Managed Services Plan today. The first step in finding the right solution is an ONSITE IT 
			 HEATH CHECK.</p>
			 
			 
        </div>
    </div>
</div>
<div class="clear"></div>

<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>No Contracts</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>No long term contract. Stay with us because we are great at what we do.</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>Customizable Plans</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>We can also customize a plan that tailors to your business</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>Spyware Removal</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>Our Managed Services performs periodic checks for spyware and malware.</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>Fixed Monthly Fee	</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>With a fixed pricing model your business is able to reliably determine IT maintenance costs.</p>
		</div>
	</div>
</div>
<div class="clear"></div>

<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>24/7 365 Days Support</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>Live Support, Email Support as well as after hours support. Rest assured we will be there when you need us.</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>Patch Management</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>Ensure all systems in your enviornment are kept up to date with the latest Microsoft Updates and Patches.</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>HDI Certified Techs</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>Our Technicians are not only technical but certified in customer service.</p>
		</div>
	</div>
</div>
<div class="grid_4">
	<div class="box round first fullpage">
		<div class="block" style="height:125px">
			<h3>Antivirus Update Checks</h3>
			<img src="/images/boxupload32.png" alt="No Contracts" class="left" />
			<p>Protect your systems and ensure they have all updated virus definition files</p>
		</div>
	</div>
</div>
<div class="clear"></div>