<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.js" type="text/javascript"></script>
<script>
$(document).ready(function() {
    $('#example').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "/location/json/browse/",
        "lengthChange": true
    } );

    $('<button id="new_location">New Location</button>').appendTo('div.dataTables_length');

    $("#new_location").click(function () {
    	window.location.href = "/location/add/index/street/" + $('div.dataTables_filter input').val();
    });
    
} );
</script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	

	<div class="box round first fullpage">
		<h2>Found the following Locations</h2>
		<div class="block">
			<table id="example" class="display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>Street</th>
						<th>city</th>
						<th>state</th>
						<th>zip</th>
					</tr>
				</thead>
				<tfoot class="foot">
					<tr>
						<th>Street</th>
						<th>city</th>
						<th>state</th>
						<th>zip</th>
					</tr>
				</tfoot>
			</table>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>


	
	
	
	
</div>

<div class="grid_3">

<?php echo $this->recent(0);?>
</div>
<div class="clear"></div>