<script src="/js/ajax/address.js" type="text/javascript"></script>
<script src="/js/ajax/plss.js" type="text/javascript"></script>
<script src="/js/ajax/latlon.js" type="text/javascript"></script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
 		<h2>Well Locations</h2>
        <div class="block">
        
        	<div class="SearchPanel">
        		<div class="grid_12 pad_4">To search start typing a Street Address, PLSS Search or Lat/Lon Search in the apropriate text box. Then click search. If no location is found click Add to create a new Location. Your most recently viewed Well locations will be in the 
        			Right Box.
        		</div>
        		<div class="clear"></div>
        		
				<form action="/location/index" class="searchForm" accept-charset="utf-8" method="post">
								
					<div class="grid_2 pad_4"><b>Address Search:</b></div>
					<div class="grid_6 pad_4">
						<input type="text" name="address" id="address" value="<?php echo $this->address?>" class="medium" maxlength="300" tabindex="1" autocomplete="off" />
						<div class="addressAutoComplete auto"><ul></ul></div>
					</div>
					<div class="clear"></div>
					
					
					<div class="grid_2 pad_4"><b>PLSS Search:</b></div>
					<div class="grid_6 pad_4">
						<input type="text" name="plss" id="plss" value="" class="medium" maxlength="300" tabindex="2" autocomplete="off" />
						<div class="plssAutoComplete auto"><ul></ul></div>
					</div>
					<div class="clear"></div>
					
					
					<div class="grid_2 pad_4"><b>Lat/Lon Search:</b></div>
					<div class="grid_6 pad_4">
						<input type="text" name="latlon" id="latlon" value="" class="medium" maxlength="300" tabindex="3" autocomplete="off" />
						<div class="latlonAutoComplete auto"><ul></ul></div>
					</div>
					
					<div class="clear"></div>
					
					<div class="grid_4">
						<input type="hidden" name="locationId" id="locationId" value="" />
						<input type="submit" name="search" id="search" value="Search" class=""/>
						<input type="button" name="add" id="add" value="Add" onclick="window.location.href ='/location/add';" />
					</div>
					<div class="clear"></div>
					
				</form>
			</div>
			
				
		</div>
	</div>
	
	<?php if(count($this->addresses) > 0 ):?>
	<div class="box round first fullpage">
 		<h2>Found the following Locations</h2>
        <div class="block">
			<table class="data display ">
				<thead>
					<tr>
						<th>ID</th>
						<th>Street</th>
						<th>City</th>
						<th>State</th>
						<th>Zipcode</th>
						<th>Modified</th>
					</tr>
				</thead>
				<tbody>
				<?php $i = 0;?>
				<?php foreach($this->addresses as $address) :?>
				<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
				<tr>
					<td><?php echo $address->id?></td>
					<td><a href="/location/view/index/id/<?php echo $address->id?>"><?php echo $address->street?></a></td>
					<td><?php echo $address->city?></td>
					<td><?php echo $address->state?></td>
					<td><?php echo $address->zip?></td>
					<td><?php echo date("M-d-Y H:i A", strtotime($address->update))?></td>
				</tr>
				<?php endforeach;?>
				</tbody>
			</table>
			
		</div>
	</div>
	<?php endif;?>
	
</div>

<div class="grid_3">

<?php echo $this->recent(0);?>
</div>
<div class="clear"></div>