<?php echo $this->MainNav();?>

<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Selected Sites Report</h2>
		<div class="block">
			<?php if($this->msg == 'delete-ok') {?>
				<div class="message success">
                	<h5>Success!</h5>
                    <p>The Report was Successfuly deleted.</p>
               </div>
			<?php }?>
			<div class="buttons">
				<a href="/report/selected-site/index" class="button left" title="Create New Selected Site Report"><span class="icon icon52"></span><span class="label">Create Selected Site Report</span></a>
			</div>
			<table class="data display ">
				<thead>
					<tr>
						<th>ID</th>
						<th>Prepaired For</th>
						<th>Date</th>
						<th>Search</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $i = 0;?>
					<?php foreach($this->selectedSites as $site) { ?>
					<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
						<td><?php echo $site->id;?></td>
						<td><a href="/report/selected-site/view/id/<?php echo $site->id;?>"><?php echo $site->name;?></a></td>
						<td><?php echo date("M d, Y", $site->date);?></td>
						<td><?php echo $site->search;?></td>
						<td>
							<div style="align:right">
							<a  href="/report/selected-site/print/id/<?php echo $site->id;?>" class="button left" title="Print Report"><span class="icon icon153"></span><span class="label"></span></a>
							<a  href="/report/selected-site/delete/id/<?php echo $site->id;?>" class="button middle" title="Delete Report"><span class="icon icon58"></span><span class="label"></span></a>
							</div>
							<br />
						</td>
					</tr>
					<?php $i++; ?>
					<?php }?>
				</tbody>
			</table>
			<br />
			<div class="buttons">
				<a href="/report/selected-site/index" class="button left" title="Create New Selected Site Report"><span class="icon icon52"></span><span class="label">Create Selected Site Report</span></a>
			</div>
		</div>
	</div>
</div>