<?php echo $this->MainNav();?>

<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Delete Selected Sites Report</h2>
		<div class="block">
			<?php if($this->form->getMessages()) {?>
				<div class="message error">
                	<h5>Error!</h5>
                    <p>
                    	The following errors where found:<br /><br />
                    	<?php foreach($this->form->getMessages() as $message) {?>
                    		<?php foreach($message as $error) {?>
                    			<?php echo$error ?> <br />
                    		<?php }?>
                    	<?php }?>
                    	<br />
                    	Please correct the above errors and save your information.
                    </p>
                </div>
			<?php } ?>
			<div class="message warning">
                	<h5>Warning!</h5>
                    <p>Are you sure you want to delete the Selected Sites Report dated: <?php echo date("m d, Y", $this->selectedSite->date);?>, prepaired for 
                    	<?php echo $this->selectedSite->name;?></p>
            </div>
			<form method="post" action="">
				<div class="grid_4 pad_4">
					<?php echo $this->form->getElement('no_csrf');?>
					<?php echo $this->form->getElement('submit');?>
				</div>
				<div class="clear"></div>
			</form>
			<br />
		</div>
	</div>
</div>