<script src="/js/toolTip.js" type="text/javascript"></script>
<?php echo $this->MainNav();?>
<div class="grid_16">
	<div class="box round first fullpage">
		<h2>View Selected Sites Report</h2>
		<div class="block">
		<div class="grid_4 pad_4"><?php if( $this->selectedSite->name):?> <b>Prepaired For:</b> <?php echo $this->selectedSite->name;?> <?php endif;?></div>
		<div class="grid_4 pad_4"><b>Date:</b> <?php Echo date("m d, Y", $this->selectedSite->date);?></div>
		<div class="clear"></div>
		
		<div class="grid_6 pad_4"><?php echo $this->selectedSite->street;?></div>
		
		<div class="clear"></div>
		
		<div class="grid_6 pad_4"><?php if( $this->selectedSite->name):?><?php echo $this->selectedSite->city;?>, <?php echo $this->selectedSite->state;?> <?php echo $this->selectedSite->zip;?><?php endif;?></div>
		<div class="clear"></div>
		
		<div class="grid_4 pad_4"><?php if( $this->selectedSite->name):?><b>Phone:</b> <?php echo $this->selectedSite->phone?><?php endif;?></div>
		<div class="grid_4 pad_4"><?php if( $this->selectedSite->name):?><b>Email:</b> <?php echo $this->selectedSite->email;?><?php endif;?></div>
			
		<div class="clear"></div>
		
		<div class="grid_4 pad_4"><b>Prepaired By:</b> <?php echo $this->selectedSite->first_name;?> <?php echo $this->selectedSite->last_name;?></div>
		<div class="grid_4 pad_4"><b>Search Term:</b> <?php echo $this->selectedSite->search;?></div>
		<div class="clear"></div>
		<br />
		
		<div class="buttons">
			<a href="/report/selected-site/all" class="button left" title="All Reports"><span class="icon icon108"></span></a>
			<a href="/report/selected-site/print/id/<?php echo $this->selectedSite->id;?>" class="button middle" title="Print Report"><span class="icon icon153"></span></a>
			<a href="/report/selected-site/delete/id/<?php echo $this->selectedSite->id;?>" class="button middle" title="Delete Report"><span class="icon icon58"></span></a>
			
		</div>
		<br />
		<table class="data display ">
			<thead>
				<tr>
					<th>Pump Tag</th>
					<th>Depth</th>
					<th>Water Level</th>
					<th>Yield</th>
					<th>Driller</th>
					<th>PLSS</th>
					<th>Lat/Lon</th>
					<th>Report Date</th>
					<th>Distance</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 0;?>
				<?php foreach($this->selectedSiteData as $data) { ?>
				<?php if (0 == $i % 2) { ?><tr class="odd"><?php } else {?><tr class="even"><?php }?>
					
					<td><?php 	echo $data->well_tag_nbr;?></td>
					<td><div onMouseover="ddrivetip('<b>Water First Found:</b> <?php echo $data->depth_first_water;?> <b>Depth Drilled:</b> <?php echo $data->depth_drilled?>','', 300)"; onMouseout="hideddrivetip()" style="cursor:pointer">
						<?php echo $data->completed_depth;?></div></td>
					<td><?php echo $data->post_static_water_level;?></td>
					<td><?php echo $data->max_yield;?></td>
					<td><?php echo $data->bonded_name_company;?></td>
					<td><div onMouseover="ddrivetip('<?php echo $data->street_of_well;?>','', 300)"; onMouseout="hideddrivetip()" style="cursor:pointer">
					
						<?php echo (int)$data->township;?> <?php echo $data->township_char;?> <?php echo (int)$data->range;?> <?php echo $data->range_char?> <?php echo $data->sctn?> <?php echo $data->qtr160?><?php echo $data->qtr40?></div></td>
					<td><?php echo $data->latitude?>/<?php echo $data->longitude;?></td>
					<td><?php echo @date("M d, Y",$data->received_date);?></td>
					<td><?php echo  number_format($data->distance, 2, '.', '');?>m</td>
				</tr>
				<?php $i++; ?>
				<?php }?>
			</tbody>
		</table>
		</div>
	</div>
</div>