<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Data Table Lists</h2>
		<div class="block">
			<h5>Location</h5>
			<blockquote>
				<a href="/city/admin/list" title="">City</a> <br />
				<a href="/state/admin/list" title="">State</a> <br />
			</blockquote>
			<br />
			
			<h5>Pump</h5>
			<blockquote>
				<a href="/pump-model/admin/list" title="">Pump Model</a> <br />
				<a href="/pump-type/admin/list" title="">Pump Type</a> <br />
				<a href="/pipe/admin/list" title="">Pipe Type</a> <br />
				<a href="/pipe-size/admin/list" title="">Pipe Size</a> <br />
			</blockquote>
			<br />
			
			<h5>Tank</h5>
			<blockquote>
				<a href="/tank-model/admin/list" title="">Tank Model</a> <br />
				<a href="/tank-type/admin/list" title="">Tank Type</a> <br />
				<a href="/tank-size/admin/list" title="">Tank Size</a> <br />
			</blockquote>
			<br />
			
			<h5>Filtration</h5>
			<blockquote>
				<a href="/filtration/admin/list" title="">Filtration Model</a> <br />
			</blockquote>
			<br />
			
		</div>
	</div>
</div>
<div class="clear"></div>