<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Filtration List</h2>
		<div class="block">
				<table class="data display">
					<thead>
						<tr>
							<th>Id</th>
							<th>Value</th>
							<th></th>
						</tr>
					</thead>
				</table>
			<div class="buttons">
				<a href="/admin/list/index" class="button left" title="Back to Admin Lists"><span class="icon icon120"></span></a>
			</div>
		</div>
	</div>
</div>