<script src="/js/fields/owner.js" type="text/javascript"></script>
<?php echo $this->MainNav();?>
<div class="grid_13">
	<div class="box round first fullpage">
		<h2>Edit Pump Test at Location <?php echo $this->location->street;?></h2>
		<div class="block">
			<?php if($this->form->getMessages()) {?>
				<div class="message error">
                	<h5>Error!</h5>
                    <p>
                    	The following errors where found:<br /><br />
                    	<?php foreach($this->form->getMessages() as $message) {?>
                    		<?php foreach($message as $error) {?>
                    			<?php echo$error ?> <br />
                    		<?php }?>
                    	<?php }?>
                    	<br />
                    	Please correct the above errors and save your information.
                    </p>
                </div>
			<?php } ?>
			<form method="post" action="">
				<div class="grid_8 pad_4"><?php echo $this->form->getElement('requirements');?></div>
				<div class="clear"></div>
				
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('source');?></div>
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('depth');?></div>
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('diameter');?></div>
				<div class="clear"></div>
				
				<div class="grid_8 pad_4"><?php echo $this->form->getElement('equipment');?></div>
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('level');?></div>
				<div class="clear"></div>
				
				<div class="grid_2 pad_4"><?php echo $this->form->getElement('vent');?></div>
				<div class="grid_2 pad_4"><?php echo $this->form->getElement('seal');?></div>
				<div class="grid_2 pad_4"><?php echo $this->form->getElement('pop_off_valve');?></div>
				<div class="clear"></div>
				
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('color');?></div>
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('taste');?></div>
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('odor');?></div>
				<div class="clear"></div>
				
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('employee');?></div>
				<div class="grid_5 pad_4"><?php echo $this->form->getElement('owner');?>
					<div class="pump">
						<div class="ownerAutoComplete auto"><ul></ul></div>
					</div>
				</div>
				<div class="clear"></div>
				
				<div class="grid_3 pad_4"><?php echo $this->form->getElement('date');?></div>
				<div class="clear"></div>
				
				<div class="grid_8 pad_4"><?php echo $this->form->getElement('remarks');?></div>
				<div class="clear"></div>
				
				<div class="grid_4 pad_4">
					<?php echo $this->form->getElement('no_csrf');?>
					<?php echo $this->form->getElement('submit');?>
				</div>
			</form>
			<div class="clear"></div>
			<br />
			<div class="buttons">
				<a href="/location/view/index/id/<?php echo $this->location->id;?>" class="button left" title="Back to Location"><span class="icon icon108"></span></a>
			</div>
			<div class="clear"></div>				
		</div>
	</div>
</div>
<div class="grid_3">
	<?php echo $this->recent(0);?>
</div>
<div class="clear"></div>